### ISSUE TITLE
Put `Add a Brave Talk Meeting` button in more prominent position around rooms/locations

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk-gcalendar-extension#11]
Currently with the extension installed, the `Add a Brave Talk Meeting` button is shown below the notification section. It should be placed near the Add Rooms/Locations area above/below Google Hangouts button. 

![image](https://user-images.githubusercontent.com/17010094/154993145-a4acbb9b-911b-4d10-a3e1-09d98de1dddc.png)

**Comment by mrose17** [comment]
Now live on the google chrome store!
