### ISSUE TITLE
Brave Talk icon on Chrome Web Store should be transparent

### ISSUE THREAD

**Issue by stephendonner** [brave/brave-talk-gcalendar-extension#13]
Summary:

Brave Talk icon on Chrome Web Store should be transparent

Steps:
1. new profile
2. launch Brave
3. load `https://chrome.google.com/webstore/detail/brave-talk-for-google-cal/nimfmkdcckklbkhjjkmbjfcpaiifgamg`
4. open `brave://settings/appearance`
5. choose `Dark`
6. back on the Google Chrome Store, click on `Add to Brave`
7. look at the resulting Brave Talk icon

Actual Results:

<img width="1785" alt="Screen Shot 2022-02-15 at 2 24 29 PM" src="https://user-images.githubusercontent.com/387249/154160267-fb2b2ae4-e703-4dce-819f-b511cb0ca8ef.png">

Expected Results:

Should have transparency, so there's no white-on-black-background in the icon.

cc @rebron @bradleyrichter @mrose17 @tackley

**Comment by mrose17** [comment]
it appears to be an issue on the chrome store itself. i'm having difficulty uploading now, but, in dark mode, go to https://chrome.google.com/webstore/detail/save-to-google-drive/gmbmikajjgmnabiglmofipeabaddhgne and click on "Add to Brave" and you'll see the google drive icon show up with a white square underneath. i've seen this on other extensions.

**Comment by mrose17** [comment]
This is a "can't-fix". the issue appears to be with the google chrome store itself, here's an example of what you see with an extension written by google themselves...
![Screen Shot 2022-03-21 at 10 00 56](https://user-images.githubusercontent.com/400552/159277311-d811044e-f370-4209-87ac-4e95c47b7008.png)
Note that we experimented with a couple of PNGs known to have a transparent background, and still no luck.
