### ISSUE TITLE
"Add meeting" button fails to open new instance of Brave Talk with new calendar entries

### ISSUE THREAD

**Issue by lukaslevert** [brave/brave-talk-gcalendar-extension#19]
When attempting to add a meeting link via Brave Talk on a new calendar entry, the button fails to execute anything. Upon editing an existing calendar entry, I am able to successfully add a Brave Talk meeting, however this requires several more steps than expected when creating new entries, as well as at minimum two email notifications to meeting participants for the creation and editing of the entry.

**Comment by kdogdavenport** [comment]
Redipient: NA ugh TY
