### ISSUE TITLE
Icon has a white background when installing in dark mode

### ISSUE THREAD

**Issue by fmarier** [brave/brave-talk-gcalendar-extension#8]
From https://github.com/brave/brave-browser/issues/20826#issuecomment-1028244728:

![Screenshot from 2022-02-02 12-25-19](https://user-images.githubusercontent.com/167821/152452335-f0135051-b52f-4202-b805-26f53eb3628a.png)

**Comment by mrose17** [comment]
OBE - the window above no longer appears as the extension is now in the Chrome store. (It is unclear why the icon, which has a transparent background, shows up with a white background...)
