### ISSUE TITLE
Can we purge jQuery?

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-talk-gcalendar-extension#9]
jQuery is only being used for things like element-creation and/or lookup, changing text and attributes on nodes, and appending nodes to various parts of the DOM. This can all be done pretty reliably without jQuery, saving us ~80-90 kb (and some minor performance gains) in the end, while freeing us up from an outside dependency.

**Comment by tackley** [comment]
Re-opening as not actually published in the store yet.

**Comment by mrose17** [comment]
Now live on the google chrome store... Thanks @jonathansampson for the PR
